[build]
pre-build = [
    "apt-get update && apt-get install --assume-yes --no-install-recommends cmake"
]

[target.mipsel-unknown-linux-musl]
build-std = true

[target.mips-unknown-linux-musl]
build-std = true
